<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

	<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	<PackageId>Swagger.Localization</PackageId>
	<Version>0.0.1</Version>
	<Authors>BaHooo</Authors>
	<Description>Universal library for Swagger documentation localization in ASP.NET Core using .resx files. Supports UI language switching, model descriptions, and parameter localization.</Description>
	<PackageTags>swagger localization resx aspnetcore openapi documentation i18n</PackageTags>
	<PackageLicenseExpression>MIT</PackageLicenseExpression>
	<RepositoryUrl>https://github.com/bahooo22/Swagger.Localization</RepositoryUrl>
	<RepositoryType>git</RepositoryType>
	<IncludeSymbols>true</IncludeSymbols>
	<SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

	<ItemGroup>
		<EmbeddedResource Include="SwaggerUI\index.html" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.6" />
		<PackageReference Include="Microsoft.Extensions.Localization" Version="9.0.10" />
		<PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="9.0.6" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Resources\*.resx">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</EmbeddedResource>
	</ItemGroup>
</Project>
